# Generated by Django 4.1.7 on 2023-04-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codEspecialidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=30)),
            ],
        ),
    ]
