# Generated by Django 4.1.7 on 2023-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiespecialidad', '0002_alter_especialidad_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(choices=[['neuro', 'NeurologÃ\xada'], ['cardio', 'CardiologÃ\xada'], ['derma', 'DermatologÃ\xada']], max_length=35),
        ),
    ]
