# Generated by Django 4.1.7 on 2023-06-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiespecialidad', '0004_alter_especialidad_guidespecialista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='guidEspecialista',
        ),
    ]
