# Generated by Django 4.1.7 on 2023-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteM',
            fields=[
                ('IdPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCompletoPac', models.CharField(max_length=90)),
                ('FechaNacimientoPac', models.DateField()),
                ('cedulaPac', models.IntegerField(unique=True)),
                ('telefonoPac', models.CharField(max_length=10)),
                ('correoPac', models.EmailField(max_length=254, unique=True)),
                ('ciudadPac', models.CharField(max_length=90)),
            ],
        ),
    ]
