# Generated by Django 4.1.7 on 2023-05-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreCompletoMed', models.CharField(max_length=90)),
                ('NumeroTarjetaMed', models.CharField(max_length=30)),
                ('cedulaMed', models.IntegerField(null=True)),
                ('telefonoMed', models.CharField(max_length=10)),
                ('correoMed', models.EmailField(max_length=254, null=True)),
                ('ciudadMed', models.CharField(choices=[['BogotÃ¡', 'MedellÃ\xadn'], ['Cali', 'Barranquilla'], ['Cartagena', 'CÃºcuta'], ['Bucaramanga', 'Pereira'], ['Santa Marta', 'IbaguÃ©'], ['Villavicencio', 'Valledupar'], ['Manizales', 'Pasto'], ['Armenia', 'MonterÃ\xada'], ['Neiva', 'PopayÃ¡n'], ['Sincelejo', 'Riohacha'], ['Tunja', 'QuibdÃ³'], ['Florencia', 'Yopal'], ['Mocoa', 'San AndrÃ©s']], max_length=100, null=True)),
            ],
        ),
    ]
