# Generated by Django 4.1.7 on 2023-03-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.IntegerField(primary_key=True, serialize=False)),
                ('cedulaMed', models.IntegerField()),
                ('nombreMed', models.CharField(max_length=15)),
                ('apellidoMed', models.CharField(max_length=15)),
                ('telefonoMed', models.IntegerField()),
                ('correoMed', models.EmailField(max_length=254)),
                ('hojaDeVidaMed', models.BinaryField()),
                ('codEspecialidadM', models.IntegerField()),
            ],
        ),
    ]
