# Generated by Django 4.1.7 on 2023-03-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAlergia', models.BigIntegerField()),
                ('tipoAlergia', models.CharField(max_length=20)),
                ('descripcionAlergia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEnfermedades', models.IntegerField()),
                ('tipoEnfermedades', models.CharField(max_length=30)),
                ('descripcionEnfermedades', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoHistorial', models.BigIntegerField()),
                ('descripcionEventos', models.TextField()),
                ('codAlergiaH', models.IntegerField()),
                ('codMedicamentosH', models.IntegerField()),
                ('codEnfermedadesH', models.IntegerField()),
                ('codExamenesH', models.IntegerField()),
                ('idPacienteH', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamnetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codMedicacion', models.IntegerField()),
                ('tipoMedicacion', models.CharField(max_length=30)),
                ('descripcionMedicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('cedulaPac', models.IntegerField()),
                ('nombrePac', models.CharField(max_length=15)),
                ('apellidoPac', models.CharField(max_length=15)),
                ('edadPac', models.IntegerField()),
                ('telefonoPac', models.IntegerField()),
                ('correoPac', models.EmailField(max_length=254)),
                ('direccionPac', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.IntegerField()),
                ('nombreProd', models.CharField(max_length=15)),
                ('descripcionProd', models.TextField()),
                ('cantidadProd', models.IntegerField()),
                ('precioProd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProveedor', models.IntegerField()),
                ('cedulaProv', models.BigIntegerField()),
                ('nombreProv', models.CharField(max_length=15)),
                ('apellidoProv', models.CharField(max_length=15)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigoCita', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCM', models.DateField()),
                ('horaCM', models.DateTimeField()),
                ('descripcionCM', models.TextField()),
                ('codTipoCitaC', models.IntegerField()),
                ('confirmacionCM', models.CharField(max_length=5)),
                ('idPacienteC', models.IntegerField()),
                ('idMedicoC', models.IntegerField()),
            ],
        ),
    ]
