# Generated by Django 4.1.7 on 2023-06-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_medico_k'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='k',
        ),
    ]
