# Generated by Django 4.1.7 on 2023-05-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_medico_ciudadmed_alter_medico_idmedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='ciudadMed',
        ),
    ]
