# Generated by Django 4.1.7 on 2023-03-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alergias_enfermedades_historialclinico_medicamnetos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEspecialidad', models.BigIntegerField()),
                ('Especialidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codExamenes', models.IntegerField()),
                ('tipoExamenes', models.CharField(max_length=30)),
                ('descripcionExamenes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProveedorPP', models.BigIntegerField()),
                ('codigoProductoPP', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoReclamo', models.IntegerField()),
                ('fechaRec', models.DateField()),
                ('codTipoReclamoR', models.IntegerField()),
                ('descripcionRec', models.TextField()),
                ('idPacienteR', models.BigIntegerField()),
                ('idMedico', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codTipoReclamo', models.IntegerField()),
                ('tipoReclamo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codTipoCita', models.BigIntegerField()),
                ('tipoCita', models.BigIntegerField()),
            ],
        ),
    ]
