# Generated by Django 4.1.7 on 2023-04-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_especialidad_examenes_proveedorproducto_reclamo_tipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alergias',
        ),
        migrations.DeleteModel(
            name='Enfermedades',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Examenes',
        ),
        migrations.DeleteModel(
            name='HistorialClinico',
        ),
        migrations.DeleteModel(
            name='Medicamnetos',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='ProveedorProducto',
        ),
        migrations.DeleteModel(
            name='Reclamo',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
