# Generated by Django 4.1.7 on 2023-05-30 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_medico_ciudadmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ciudadMed',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
