# Generated by Django 4.1.7 on 2023-04-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_delete_alergias_delete_enfermedades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEspecialidad', models.BigIntegerField()),
                ('Especialidad', models.CharField(max_length=30)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.medico')),
            ],
        ),
    ]
