# Generated by Django 4.1.7 on 2023-06-14 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_medico_idespecialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='IdCiudad',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
