# Generated by Django 4.1.7 on 2023-06-16 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_medico_idciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='direccionConsultorio',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
