# Generated by Django 4.1.7 on 2023-05-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_delete_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='telefonoMed',
            field=models.CharField(max_length=10),
        ),
    ]
