# Generated by Django 4.1.7 on 2023-05-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_medico_telefonomed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='apellidoMed',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombreMed',
            field=models.CharField(max_length=35),
        ),
    ]
