# Generated by Django 4.1.7 on 2023-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_medico_direccionconsultorio_medico_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='direccionConsultorio',
            field=models.CharField(max_length=80),
        ),
    ]
