# Generated by Django 4.1.7 on 2023-05-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_medico_apellidomed_alter_medico_nombremed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='apellidoMed',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='codEspecialidadM',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='hojaDeVidaMed',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nombreMed',
        ),
    ]
