# Generated by Django 4.1.7 on 2023-05-05 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_remove_medico_apellidomed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='NombreCompletoMed',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='NumeroTarjetaMed',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
