# Generated by Django 4.1.7 on 2023-05-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_medico_nombrecompletomed_medico_numerotarjetamed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='NumeroTarjetaMed',
            field=models.CharField(max_length=50),
        ),
    ]
