# Generated by Django 4.1.7 on 2023-05-13 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_medico_nombrecompletomed_medico_numerotarjetamed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ciudad',
            field=models.CharField(choices=[['BogotÃ¡', 'MedellÃ\xadn'], ['Cali', 'Barranquilla'], ['Cartagena', 'CÃºcuta'], ['Bucaramanga', 'Pereira'], ['Santa Marta', 'IbaguÃ©'], ['Villavicencio', 'Valledupar'], ['Manizales', 'Pasto'], ['Armenia', 'MonterÃ\xada'], ['Neiva', 'PopayÃ¡n'], ['Sincelejo', 'Riohacha'], ['Tunja', 'QuibdÃ³'], ['Florencia', 'Yopal'], ['Mocoa', 'San AndrÃ©s']], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
