# Generated by Django 4.1.7 on 2023-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_medico_numerotarjetamed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='NombreCompletoMed',
            field=models.CharField(max_length=80),
        ),
    ]
