# Generated by Django 4.1.7 on 2023-06-17 16:50

import agendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEspecialista', models.CharField(max_length=90)),
                ('IdMedico', models.CharField(max_length=90)),
                ('Fecha', models.DateField(validators=[agendar.models.validate_future_date])),
                ('Motivo', models.TextField()),
                ('Hora', models.TimeField(unique_for_date='Fecha')),
                ('Tipodeconsulta', models.CharField(max_length=80)),
            ],
        ),
    ]
