# Generated by Django 4.1.7 on 2023-06-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Motivo', models.TextField()),
                ('Hora', models.TimeField()),
                ('Tipodeconsulta', models.CharField(max_length=80)),
            ],
        ),
    ]
