# Generated by Django 4.1.7 on 2023-06-26 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='Estados',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
