# Generated by Django 4.1.7 on 2023-06-27 02:20

import agendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='Hora',
            field=models.TimeField(unique_for_date='Fecha', validators=[agendar.models.validate_hour_separation]),
        ),
    ]
