# Generated by Django 4.1.7 on 2023-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='IdEspecialista',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agendar',
            name='IdMedico',
            field=models.IntegerField(null=True),
        ),
    ]
