# Generated by Django 4.1.7 on 2023-06-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0002_agendar_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='Estados',
            field=models.CharField(max_length=50),
        ),
    ]
