# Generated by Django 4.1.7 on 2023-06-14 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0002_agendar_idespecialista_agendar_idmedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='IdEspecialista',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendar',
            name='IdMedico',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
