# Generated by Django 4.1.7 on 2023-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0006_agendar_idpaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendar',
            name='id',
        ),
        migrations.AddField(
            model_name='agendar',
            name='IdCita',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
