# Generated by Django 4.1.7 on 2023-06-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendar', '0007_remove_agendar_id_agendar_idcita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendar',
            name='IdEspecialista',
        ),
    ]
