# Generated by Django 4.1.7 on 2023-04-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('cedulaPac', models.IntegerField()),
                ('nombrePac', models.CharField(max_length=15)),
                ('apellidoPac', models.CharField(max_length=15)),
                ('edadPac', models.IntegerField()),
                ('telefonoPac', models.IntegerField()),
                ('correoPac', models.EmailField(max_length=254)),
                ('direccionPac', models.CharField(max_length=30)),
            ],
        ),
    ]
