# Generated by Django 4.1.7 on 2023-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0002_paciente_activopac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ActivoPac',
            field=models.BooleanField(),
        ),
    ]
