# Generated by Django 4.1.7 on 2023-05-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0002_alter_paciente_telefonopac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellidoPac',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombrePac',
            field=models.CharField(max_length=35),
        ),
    ]
