# Generated by Django 4.1.7 on 2023-05-30 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0003_remove_paciente_ciudadpac'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ciudadPac',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
