# Generated by Django 4.1.7 on 2023-05-05 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0004_remove_paciente_apellidopac_remove_paciente_edadpac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='NombreCompletoPac',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
