# Generated by Django 4.1.7 on 2023-06-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0004_paciente_ciudadpac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccionPac',
            field=models.CharField(max_length=50),
        ),
    ]
