# Generated by Django 4.1.7 on 2023-05-05 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0005_paciente_nombrecompletopac'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='FechaNacimientoPac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
