# Generated by Django 4.1.7 on 2023-05-16 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0007_ciudad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudadPac',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
