# Generated by Django 4.1.7 on 2023-05-07 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0007_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
