# Generated by Django 4.1.7 on 2023-05-07 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipaciente', '0008_remove_ciudad_ciudad_ciudad_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
