# Generated by Django 4.1.7 on 2023-06-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoM',
            fields=[
                ('IdMedico', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCompletoMed', models.CharField(max_length=80)),
                ('NumeroTarjetaMed', models.CharField(max_length=50)),
                ('CedulaMed', models.IntegerField(null=True)),
                ('CorreoMed', models.EmailField(max_length=254, null=True)),
                ('TelefonoMed', models.CharField(max_length=10)),
                ('CiudadMed', models.CharField(max_length=90)),
                ('Especialidad', models.CharField(max_length=50)),
                ('DireccionConsultorio', models.CharField(max_length=50)),
                ('IdEspecialidad', models.CharField(max_length=80)),
                ('IdCiudad', models.CharField(max_length=90)),
                ('HoraInicio', models.CharField(max_length=1000)),
                ('HoraFinal', models.CharField(max_length=1000)),
                ('FechasDisponibilidad', models.CharField(max_length=1000)),
                ('PerfilProfesional', models.CharField(max_length=500)),
                ('Activo', models.BooleanField(null=True)),
            ],
        ),
    ]
