# Generated by Django 4.1.7 on 2023-06-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicom',
            old_name='IdEspecialidad',
            new_name='NombreEspecialidad',
        ),
    ]
