# Generated by Django 4.1.7 on 2023-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_remove_medicom_idciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicom',
            name='Activo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicom',
            name='DireccionConsultorio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicom',
            name='FechasDisponibilidad',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicom',
            name='HoraFinal',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicom',
            name='HoraInicio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicom',
            name='PerfilProfesional',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
