# Generated by Django 4.1.7 on 2023-06-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_alter_medicom_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicom',
            name='HoraFinal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicom',
            name='HoraInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
