# Generated by Django 4.1.7 on 2023-06-28 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_alter_medicom_horafinal_alter_medicom_horainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicom',
            name='guidEspecialista',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
