# Generated by Django 4.1.7 on 2023-06-29 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0007_medicom_guidespecialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicom',
            name='fotoPerfil',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
