# Generated by Django 4.1.7 on 2023-06-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_medicom_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicom',
            name='guidEspecialista',
            field=models.UUIDField(blank=True),
        ),
    ]
